<a href="https://colab.research.google.com/github/khushi3117/Python-Projects/blob/main/dataanalaytics_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## data analaytics-->

# Table of Content

1. **[What is Python Numpy](#python_numpy)**
2. **[Functions to Create Array](#functions)**
3. **[Attributes and Functions on Array](#operations)**
4. **[Indexing Array](#Indexing)**
5. **[Slicing Array](#Slicing)**
6. **[Operations on a 1D Array](#operations_1d)**
7. **[Operations on a 2D Array](#operations_2d)**
8. **[Arithmetic Functions in Numpy](#arithmetic_functions)**
9. **[Concatenation of Array](#concatenation)**
10. **[Stacking of Array](#stacking)**
11. **[Splitting of Array](#splitting)**
12. **[Iterating Numpy Array](#Iterating)**
13. **[numpy iteration method] (any,all,where)**

2. **[Functions to Create Array](#functions)**

In [ ]:
## arange
import numpy as np
array=np.arange(10,40)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [ ]:
array.ndim

1

In [ ]:
array=np.arange(10,40).reshape(10,3)
array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

In [ ]:
## random.random-->get the element between 0 to 1,half open interval it means 0 include but 1 is excluded
array=np.random.random((5,2))

In [ ]:
## random.randint--ranom integer number
np.random.randint(10,40,(5,4))

array([[26, 31, 24, 35],
       [38, 37, 35, 25],
       [27, 31, 26, 21],
       [14, 11, 27, 38],
       [29, 39, 28, 24]])

In [ ]:
## random.randn
np.random.randn(20)

array([ 0.29143986, -1.7106757 , -1.16828124,  0.03071937,  2.25854356,
        1.31423189, -2.02945303,  0.28755326,  0.15403983, -0.18085089,
        1.45459709,  0.56377254, -0.27101182,  0.89295925, -0.67838524,
       -0.71448599, -2.71195858,  0.5070622 , -0.66273357,  1.5484913 ])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

#. Attributes and Functions on Array

In [ ]:
array

array([[0.99348492, 0.4656289 ],
       [0.37176803, 0.58679764],
       [0.43284128, 0.97606759],
       [0.18349822, 0.52613042],
       [0.25360443, 0.82038714]])

In [ ]:
## shape-->no of rows and columns
array.shape

(5, 2)

In [ ]:
## size--length of data
array.size

10

In [ ]:
## dtype-->container inside data
array.dtype

dtype('float64')

In [ ]:
## ndim
array.ndim

2

In [ ]:
## itemsize-->memory allocation
array.itemsize

8

## indexing and slicing

In [ ]:
## indexing
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array[4]

np.int64(4)

In [ ]:
array[4:]

array([4, 5, 6, 7, 8, 9])

In [ ]:
array1=np.arange(15).reshape(5,3)
array1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
array1[1:3,1:]

array([[4, 5],
       [7, 8]])

In [ ]:
array1[:,2]

array([ 2,  5,  8, 11, 14])

In [ ]:
array2=np.arange(10,30).reshape(5,4)
array2

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [ ]:
## get the element from ist rows-->13
## get the element from 2nd and 3rd rows-->17,18
## get element from 3rd rows-->entire rows
array2[1,3], array2[2,0]

(np.int64(17), np.int64(18))

In [ ]:
array2[2,1]*=5
array2

array([[ 10,  11,  12,  13],
       [ 14,  15,  16,  17],
       [ 18, 120,  20,  21],
       [ 22,  23,  24,  25],
       [ 26,  27,  28,  29]])

In [ ]:

# first array
prices = np.array([120,230,310,410,150])

# print the array
print("The first array is",prices,"has length",len(prices))

# second array
quantity = np.arange(5)

# print the array
print("The second array is",quantity,"has length",len(quantity))

The first array is [120 230 310 410 150] has length 5
The second array is [0 1 2 3 4] has length 5

In [ ]:
prices+quantity

array([120, 231, 312, 413, 154])

In [ ]:
prices+=quantity

In [ ]:
prices

array([120, 231, 312, 413, 154])

In [ ]:
margin=np.array([1,2,3,4])
prices+margin

ValueError: operands could not be broadcast together with shapes (5,) (4,)

In [ ]:
prices

array([120, 231, 312, 413, 154])

In [ ]:
prices[prices>300]

array([312, 413])

In [ ]:
## operation in 2d


# declare two arrays
# first array
quanitity_A = np.array([[33,12],[70,61]])

# print the array
print("The first array is \n",quanitity_A)

# second array
quanitity_B  = np.array([[43,51],[72,81]])

# print the array
print("The second array is \n",quanitity_B)

The first array is
 [[33 12]
 [70 61]]
The second array is
 [[43 51]
 [72 81]]

In [ ]:
quanitity_A*quanitity_B

array([[1419,  612],
       [5040, 4941]])

In [ ]:
quanitity_C=np.array([45,18])
quanitity_A+quanitity_C

array([[ 78,  30],
       [115,  79]])

## MATRIX MULTIPICATION

In [ ]:
quanitity_A @ quanitity_B

array([[2283, 2655],
       [7402, 8511]])

In [ ]:
quanitity_A.dot(quanitity_B)

array([[2283, 2655],
       [7402, 8511]])

In [ ]:
prices,quantity

(array([120, 231, 312, 413, 154]), array([0, 1, 2, 3, 4]))

In [ ]:
## airthmatic operarions
np.sum([prices,quantity])

np.int64(1240)

In [ ]:

np.sum([prices,quantity],axis=0)

array([120, 232, 314, 416, 158])

In [ ]:
np.sum([prices,quantity],axis=1)

array([1230,   10])

In [ ]:
## power
np.power(prices,2)

array([ 14400,  53361,  97344, 170569,  23716])

In [ ]:
np.min(prices)

np.int64(120)

In [ ]:
# create a 2D array
scores_player_1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
scores_player_1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# create a 2D array
scores_player_2 = np.array([[5, 6, 3],
                 [4, 9, 6]])
scores_player_2

array([[5, 6, 3],
       [4, 9, 6]])

In [ ]:
np.concatenate([scores_player_1,scores_player_2],axis=1)

array([[1, 2, 3, 5, 6, 3],
       [4, 5, 6, 4, 9, 6]])

## STACKING-->COMBINE ONE OR MORE TABLE TO FORM A SINGLE ARRAY WITH HIGHER DIMENSION

In [ ]:
num_array_1 = np.array([[1, 2, 3], [4, 5, 6]])
num_array_2 = np.array([[7, 8, 9], [10, 11, 12]])
print(num_array_1)
print(num_array_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

In [ ]:
np.stack([num_array_1,num_array_2])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
np.stack([num_array_1,num_array_2],axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
np.stack([num_array_1,num_array_2],axis=1)

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [ ]:
np.hstack([num_array_1,num_array_2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.vstack([num_array_1,num_array_2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.dstack([num_array_1,num_array_2])

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

## splitting-->split an array to subset of array

In [ ]:
array=np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.split(array,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
np.split(array,2)

ValueError: array split does not result in an equal division

In [ ]:
np.array_split(array,4)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [ ]:
np.array_split(array,2)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]

In [ ]:
np.mean(array)

np.float64(5.0)

In [ ]:
np.median(array)

np.float64(5.0)

In [ ]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## np.where
np.where(array%2==0,array,0)

array([0, 2, 0, 4, 0, 6, 0, 8, 0])

## PANDAS-->PANEL+DATA
## USED FOR MANIPULATION(DATA PREPROCESSING-->CLEAN,OUTLIER,TRANSFORM,DATA TYPE,CAT TO NUM,NULL VALUE ETC..)

-->LAZY

## data structure
-->series

-->dataframe

In [ ]:
import seaborn as sns
resto=sns.load_dataset("tips")
resto

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
resto.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
resto.day.unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [ ]:
resto.day.nunique()

4

## PANDAS--->

## DATA STRUCURE-->

**1.Series-->one dimensional data type with containg mixed data types,by default index will be defined for each rows

**2.DataFrame-->two dimensional data type containing mied data type..

In [ ]:
##SERIES
lst=[45,15,65,52,48,45,58,72]
lst

[45, 15, 65, 52, 48, 45, 58, 72]

In [ ]:
import pandas as pd
pd.Series(lst)

0    45
1    15
2    65
3    52
4    48
5    45
6    58
7    72
dtype: int64

In [ ]:
subject=["python","c++","java","c"]
marks=[45,52,96,69]
cgpa=[4.5,5.2,9.6,6.9]

type(pd.Series([subject,marks,cgpa]))

pandas.core.series.Series

In [ ]:
pd.Series(marks,subject)

python    45
c++       52
java      96
c         69
dtype: int64

In [ ]:
import numpy as np
x=np.arange(10,20)
series=pd.Series(x)
series

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [ ]:
series.shape

(10,)

In [ ]:
series.ndim

1

In [ ]:
series.head(2)

0    10
1    11
dtype: int64

In [ ]:
series.tail(1)

9    19
dtype: int64

In [ ]:
series[4:7]

4    14
5    15
6    16
dtype: int64

## DATAFRAME-->ROWS AND COLUMNS

In [ ]:
subject=["python","c++","java","c"]
marks=[45,52,96,69]
cgpa=[4.5,5.2,9.6,6.9]

pd.DataFrame([subject,marks,cgpa],index=["subject","marks","cgpa"]).T

  subject marks cgpa
0  python    45  4.5
1     c++    52  5.2
2    java    96  9.6
3       c    69  6.9

In [ ]:
## dictionary to dataf
data={"subject":["python","c++","java","c"],
      "marks":(78,56,96,26),
      "cgpa":[7.8,5.6,9.6,2.6]}

data

{'subject': ['python', 'c++', 'java', 'c'],
 'marks': (78, 56, 96, 26),
 'cgpa': [7.8, 5.6, 9.6, 2.6]}

In [ ]:
pd.DataFrame(data)

  subject  marks  cgpa
0  python     78   7.8
1     c++     56   5.6
2    java     96   9.6
3       c     26   2.6

In [ ]:
## series to dataframe
subject=pd.Series(["python","c++","java","c"])
marks=pd.Series([45,52,96,69])
cgpa=pd.Series([4.5,5.2,9.6,6.9])
pd.DataFrame([subject,marks,cgpa],index=["subject","marks","cgpa"]).T

  subject marks cgpa
0  python    45  4.5
1     c++    52  5.2
2    java    96  9.6
3       c    69  6.9

In [ ]:
## read the data from different sources
df=pd.read_csv("/content/Admission_Predict (1).csv")
df

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,1
1,2,324,107,4,4.0,4.5,8.87,1,1
2,3,316,104,3,3.0,3.5,8.00,1,0
3,4,322,110,3,3.5,2.5,8.67,1,1
4,5,314,103,2,2.0,3.0,8.21,0,0
...,...,...,...,...,...,...,...,...,...
395,396,324,110,3,3.5,3.5,9.04,1,1
396,397,325,107,3,3.0,3.5,9.11,1,1
397,398,330,116,4,5.0,4.5,9.45,1,1
398,399,312,103,3,3.5,4.0,8.78,0,0
399,400,333,117,4,5.0,4.0,9.66,1,1

In [ ]:
pd.read_excel("Data_Train.xlsx")

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [ ]:
pd.read_json("iris.json")

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [ ]:
import seaborn as sns
resto=sns.load_dataset("tips")
resto.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
## check the shape of the data
resto.shape

(243, 7)

In [ ]:
## check the dtypes for each columns
resto.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [ ]:
## check the duplicates data
resto.duplicated().sum()

np.int64(1)

In [ ]:
resto[resto.duplicated()]

     total_bill  tip     sex smoker   day   time  size
202        13.0  2.0  Female    Yes  Thur  Lunch     2

In [ ]:
## drop duplicates
resto.drop_duplicates(inplace=True)

In [ ]:
##
type(resto)

pandas.core.frame.DataFrame

In [ ]:
type(resto.day)

pandas.core.series.Series

In [ ]:
resto.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  243 non-null    float64
 1   tip         243 non-null    float64
 2   sex         243 non-null    category
 3   smoker      243 non-null    category
 4   day         243 non-null    category
 5   time        243 non-null    category
 6   size        243 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 9.1 KB

In [ ]:
## statistical inference
resto.describe()

       total_bill         tip        size
count  243.000000  243.000000  243.000000
mean    19.813868    3.002387    2.572016
std      8.910071    1.385002    0.952356
min      3.070000    1.000000    1.000000
25%     13.380000    2.000000    2.000000
50%     17.810000    2.920000    2.000000
75%     24.175000    3.575000    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
resto.describe(include=object)

ValueError: No objects to concatenate

In [ ]:
resto.sex=resto.sex.astype(object)
resto.smoker=resto.smoker.astype(object)
resto.day=resto.day.astype(object)
resto.time=resto.time.astype(object)

In [ ]:
resto.dtypes

total_bill    float64
tip           float64
sex            object
smoker         object
day            object
time           object
size            int64
dtype: object

In [ ]:
resto.describe(include=object)

         sex smoker  day    time
count    243    243  243     243
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

In [ ]:
## indexing and slicing
# indexing
resto.head(1)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2

In [ ]:
resto[10:16]

    total_bill   tip     sex smoker  day    time  size
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
15       21.58  3.92    Male     No  Sun  Dinner     2

In [ ]:
resto[10:16,0:3]

InvalidIndexError: (slice(10, 16, None), slice(0, 3, None))

In [ ]:
## loc->location based data
resto.loc[10:16,["total_bill","sex"]]

    total_bill     sex
10       10.27    Male
11       35.26  Female
12       15.42    Male
13       18.43    Male
14       14.83  Female
15       21.58    Male
16       10.33  Female

In [ ]:
## we need to add new data
resto.tail(1)

     total_bill  tip     sex smoker  day    time  size
244       28.25  3.0  Female     No  Sat  Dinner     3

In [ ]:
resto.loc[244]=[28.25,3.0,"Female","No","Sat","Dinner",3]

In [ ]:
resto["per_head_price"]=resto.total_bill/resto.size*1000
resto.head()

   total_bill   tip     sex smoker  day    time  size  per_head_price
0       16.99  1.01  Female     No  Sun  Dinner     2        8.703893
1       10.34  1.66    Male     No  Sun  Dinner     3        5.297131
2       21.01  3.50    Male     No  Sun  Dinner     3       10.763320
3       23.68  3.31    Male     No  Sun  Dinner     2       12.131148
4       24.59  3.61  Female     No  Sun  Dinner     4       12.597336

In [ ]:
## iloc-->index based location
resto.iloc[10:16,0:3]

    total_bill   tip     sex
10       10.27  1.71    Male
11       35.26  5.00  Female
12       15.42  1.57    Male
13       18.43  3.00    Male
14       14.83  3.02  Female
15       21.58  3.92    Male

In [ ]:
## check the null values in dataset
resto.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
## conditional statement
resto[(resto.total_bill>30) & (resto.sex=="Male") & (resto.time=="Dinner")]

     total_bill    tip   sex smoker  day    time  size  per_head_price
23        39.42   7.58  Male     No  Sat  Dinner     4       20.194672
39        31.27   5.00  Male     No  Sat  Dinner     3       16.019467
44        30.40   5.60  Male     No  Sun  Dinner     4       15.573770
47        32.40   6.00  Male     No  Sun  Dinner     4       16.598361
56        38.01   3.00  Male    Yes  Sat  Dinner     4       19.472336
59        48.27   6.73  Male     No  Sat  Dinner     4       24.728484
95        40.17   4.73  Male    Yes  Fri  Dinner     4       20.578893
112       38.07   4.00  Male     No  Sun  Dinner     3       19.503074
156       48.17   5.00  Male     No  Sun  Dinner     6       24.677254
167       31.71   4.50  Male     No  Sun  Dinner     4       16.244877
170       50.81  10.00  Male    Yes  Sat  Dinner     3       26.029713
173       31.85   3.18  Male    Yes  Sun  Dinner     2       16.316598
175       32.90   3.11  Male    Yes  Sun  Dinner     2       16.854508
179       34.63   3.55  Male    Yes  Sun  Dinner     2       17.740779
180       34.65   3.68  Male    Yes  Sun  Dinner     4       17.751025
182       45.35   3.50  Male    Yes  Sun  Dinner     3       23.232582
184       40.55   3.00  Male    Yes  Sun  Dinner     2       20.773566
187       30.46   2.00  Male    Yes  Sun  Dinner     5       15.604508
207       38.73   3.00  Male    Yes  Sat  Dinner     4       19.841189
210       30.06   2.00  Male    Yes  Sat  Dinner     3       15.399590
212       48.33   9.00  Male     No  Sat  Dinner     4       24.759221
237       32.83   1.17  Male    Yes  Sat  Dinner     2       16.818648